theme: jekyll-theme-minimal

minimal_mistakes_skin: "dirt"

plugins:
  - jekyll-feed

title: Dr. Bas Peters
description: Research Scientist at Computational Geosciences Inc

collections:
  pages:
    output: true
